require 'huginn_agent'

#HuginnAgent.load 'huginn_callisto_explorer_owned_token_agent/concerns/my_agent_concern'
HuginnAgent.register 'huginn_callisto_explorer_owned_token_agent/callisto_explorer_owned_token_agent'
